openapi: 3.0.1
info:
  title: Turing BACKEND challenge
  description: 'This is Turing Backend challenge API description'
  contact:
    name: Borovkov Alexey
    email: lucky.aaz@gmail.com
  version: 1.0.0
servers:
- url: http://185.205.210.3/api
tags:
- name: Products
  description: Search by products, show product full information by id
- name: Customer
  description: Show and update customer info
paths:
  /products:
    get:
      tags:
      - Products
      summary: Search in product list
      operationId: updatePet
      parameters:
        - name: criteria[department_id]
          in: query
          description: Department ID to search products in
          required: false
          schema:
            type: integer
        - name: criteria[category_id]
          in: query
          description: Category ID to search products in
          required: false
          schema:
            type: integer
        - name: criteria[name]
          in: query
          description: Product name
          required: false
          schema:
            type: string
        - name: criteria[description]
          in: query
          description: Product name
          required: false
          schema:
            type: string
      responses:
        403:
          description: Incorrect request
          content: {}
        404:
          description: No products found
          content: {}
